CREATE TABLE IF NOT EXISTS public.messages(
    message_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    message_subject character varying NOT NULL,
    message_body text NOT NULL,
    message_created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_to integer NOT NULL,
    message_from integer NOT NULL,
    message_read boolean NOT NULL DEFAULT FALSE,
    message_archived boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT messages_pk PRIMARY KEY (message_id)
);


INSERT INTO public.messages (message_subject, message_body, message_to, message_from, message_read, message_archived)
VALUES
    ('Meeting Reminder', 'Dont forget about the meeting tomorrow at 10 AM', 123, 456, TRUE, FALSE),
    ('Task Deadline', 'Please submit the report by end of the day', 789, 456, FALSE, TRUE),
    ('Weekend Plans', 'Lets plan for a hiking trip this weekend', 456, 123, FALSE, FALSE),
    ('Birthday Celebration', 'Dont forget to buy a gift for Johns birthday', 789, 123, TRUE, FALSE),
    ('Project Update', 'The project is progressing well, keep up the good work', 123, 789, TRUE, FALSE),
    ('Vacation Approval', 'Your vacation request has been approved', 456, 789, FALSE, FALSE),
    ('New Feature Proposal', 'I have some ideas for the new feature, lets discuss', 789, 456, FALSE, FALSE),
    ('Feedback Request', 'Please provide feedback on the latest product release', 123, 456, TRUE, TRUE),
    ('Training Session', 'There will be a training session on Friday at 2 PM', 789, 123, FALSE, FALSE),
    ('Team Lunch', 'Lets have a team lunch tomorrow to celebrate the project milestone', 456, 789, FALSE, FALSE);
